server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show-sql: true
  datasource:
    url: jdbc:h2:mem:~/demo;DB_CLOSE_ON_EXIT=TRUE;MODE=MSSQLServer
    driverClassName: org.h2.Driver
    username: sa
    password:
  flyway:
    locations: ["classpath:h2/db/migration"]
logging:
  file:
    path: C:\tmg\logs\demo